--DROP TABLE CARGO
--DROP TABLE USUARIO_CARGO
--DROP TABLE USUARIO
--DROP TABLE TECNOLOGIA
--DROP TABLE CLIENTE
--DROP TABLE PROGRAMA
--DROP TABLE TECNOLOGIA
--DROP TABLE CLIENTE
--DROP TABLE PROGRAMA
--DROP TABLE ALUNO
--DROP TABLE ALUNO_TECNOLOGIA
--DROP TABLE VAGA
--DROP TABLE AVALIACAO
--DROP TABLE RESERVA_ALOCACAO
--DROP TABLE VAGA_PROGRAMA
--DROP TABLE FILES
--DROP SEQUENCE SEQ_FILE
--DROP SEQUENCE SEQ_USUARIO
--DROP SEQUENCE SEQ_CARGO
--DROP SEQUENCE SEQ_ALUNO
--DROP SEQUENCE SEQ_TECNOLOGIA
--DROP SEQUENCE SEQ_CLIENTE
--DROP SEQUENCE SEQ_VAGA
--DROP SEQUENCE SEQ_PROGRAMA
--DROP SEQUENCE SEQ_AVALIACAO
--DROP SEQUENCE SEQ_RESERVA_ALOCACAO


CREATE TABLE CARGO
(
    ID_CARGO NUMBER               NOT NULL,
    NOME     varchar2(512) UNIQUE NOT NULL,
    PRIMARY KEY (ID_CARGO)
);

CREATE TABLE USUARIO_CARGO
(
    ID_USUARIO NUMBER NOT NULL,
    ID_CARGO   NUMBER NOT NULL,
    PRIMARY KEY (ID_USUARIO, ID_CARGO),
    CONSTRAINT FK_USUARIO_CARGO_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID_CARGO),
    CONSTRAINT FK_USUARIO_CARGO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE TABLE USUARIO
(
    ID_USUARIO    NUMBER NOT NULL,
    nome_completo VARCHAR(255),
    email         VARCHAR(255) UNIQUE,
    senha         VARCHAR(255),
    foto          BLOB,
    PRIMARY KEY (ID_USUARIO)

);

CREATE TABLE TECNOLOGIA
(
    ID_TECNOLOGIA NUMBER        NOT NULL,
    NOME          VARCHAR2(255) NOT NULL,
    PRIMARY KEY (ID_TECNOLOGIA)
);

CREATE TABLE CLIENTE
(
    ID_CLIENTE NUMBER               NOT NULL,
    NOME       VARCHAR2(255)        NOT NULL,
    EMAIL      VARCHAR2(255) UNIQUE NOT NULL,
    TELEFONE   VARCHAR2(20)         NOT NULL,
    SITUACAO   VARCHAR2(20)         NOT NULL,
    PRIMARY KEY (ID_CLIENTE)
);

CREATE TABLE PROGRAMA
(
    ID_PROGRAMA  NUMBER        NOT NULL,
    NOME         VARCHAR2(255) NOT NULL,
    DESCRICAO    VARCHAR2(255) NOT NULL,
    DATA_CRIACAO DATE          NOT NULL,
    DATA_TERMINO DATE          NOT NULL,
    SITUACAO     VARCHAR2(20)  NOT NULL,
    PRIMARY KEY (ID_PROGRAMA)
);

CREATE TABLE ALUNO
(
    ID_ALUNO     NUMBER               NOT NULL,
    NOME         VARCHAR2(255)        NOT NULL,
    EMAIL        VARCHAR2(255) UNIQUE NOT NULL,
    AREA         VARCHAR2(255)        NOT NULL,
    CIDADE       VARCHAR2(255)        NOT NULL,
    ESTADO       VARCHAR2(255)        NOT NULL,
    TELEFONE     VARCHAR2(20)         NOT NULL,
    DESCRICAO    VARCHAR2(500),
    ID_PROGRAMA  NUMBER               NOT NULL,
    STATUS_ALUNO VARCHAR2(20)         NOT NULL,
    PRIMARY KEY (ID_ALUNO),
    CONSTRAINT FK_PROGRAMA_PROGRAMA FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA (ID_PROGRAMA)
);

CREATE TABLE ALUNO_TECNOLOGIA
(
    ID_TECNOLOGIA NUMBER NOT NULL,
    ID_ALUNO      NUMBER NOT NULL,
    PRIMARY KEY (ID_ALUNO, ID_TECNOLOGIA),
    CONSTRAINT FK_ALUNO_TECNOLOGIA FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID_ALUNO),
    CONSTRAINT FK_TECNOLOGIA_TECNOLOGIA FOREIGN KEY (ID_TECNOLOGIA) REFERENCES TECNOLOGIA (ID_TECNOLOGIA)
);

CREATE TABLE VAGA
(
    CODIGO_VAGA         NUMBER        NOT NULL,
    ID_CLIENTE          NUMBER UNIQUE NOT NULL,
    NOME                VARCHAR2(255) NOT NULL,
    QUANTIDADE          NUMBER        NOT NULL,
    QUANTIDADE_ALOCADOS NUMBER        NOT NULL,
    DATA_ABERTURA       DATE          NOT NULL,
    DATA_FECHAMENTO     DATE,
    DATA_CRIACAO        DATE          NOT NULL,
    SITUACAO            VARCHAR2(20)  NOT NULL,
    PRIMARY KEY (CODIGO_VAGA),
    CONSTRAINT FK_CLIENTE_VAGA FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
);


CREATE TABLE AVALIACAO
(
    CODIGO_AVALIACAO NUMBER       NOT NULL,
    ID_ALUNO         NUMBER       NOT NULL,
    CODIGO_VAGA      NUMBER       NOT NULL,
    DESCRICAO        VARCHAR2(500),
    NOTA             NUMBER       NOT NULL,
    TIPO_AVALIACAO   NUMBER       NOT NULL,
    DATA_AVALIACAO   DATE         NOT NULL,
    DATA_ENTREVISTA  DATE         NOT NULL,
    DATA_RESPOSTA    DATE         NOT NULL,
    DATA_CRIACAO     DATE         NOT NULL,
    SITUACAO         VARCHAR2(20) NOT NULL,
    PRIMARY KEY (CODIGO_AVALIACAO),
    CONSTRAINT FK_ALUNO_AVALIACAO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID_ALUNO),
    CONSTRAINT FK_VAGA_AVALIACAO FOREIGN KEY (CODIGO_VAGA) REFERENCES VAGA (CODIGO_VAGA)
);

CREATE TABLE RESERVA_ALOCACAO
(
    CODIGO_RESERVA_ALOCACAO NUMBER       NOT NULL,
    ID_ALUNO                NUMBER       NOT NULL,
    CODIGO_VAGA             number       NOT NULL,
    DESCRICAO               VARCHAR2(500),
    CODIGO_AVALIACAO        NUMBER       NOT NULL,
    DATA_RESERVA            DATE         NOT NULL,
    DATA_ALOCACAO           DATE,
    DATA_CANCELAMENTO       DATE,
    DATA_FINALIZACO         DATE,
    SITUACAO                VARCHAR2(20) NOT NULL,
    PRIMARY KEY (CODIGO_RESERVA_ALOCACAO, ID_ALUNO),
    CONSTRAINT FK_ALUNO_RESERVA_ALOCACAO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID_ALUNO),
    CONSTRAINT FK_VAGA_RESERVA_ALOCACAO FOREIGN KEY (CODIGO_VAGA) REFERENCES VAGA (CODIGO_VAGA),
    CONSTRAINT FK_AVALIACAO_RESERVA_ALOCACAO FOREIGN KEY (CODIGO_AVALIACAO) REFERENCES AVALIACAO (CODIGO_AVALIACAO)
);


CREATE TABLE VAGA_PROGRAMA
(
    CODIGO_VAGA NUMBER NOT NULL,
    ID_PROGRAMA NUMBER NOT NULL,
    PRIMARY KEY (CODIGO_VAGA, ID_PROGRAMA),
    CONSTRAINT FK_VAGA_PROGRAMA FOREIGN KEY (CODIGO_VAGA) REFERENCES VAGA (CODIGO_VAGA),
    CONSTRAINT FK_PROGRAMA_VAGA_PROGRAMA FOREIGN KEY (ID_PROGRAMA) REFERENCES PROGRAMA (ID_PROGRAMA)
);

CREATE TABLE FILES
(
    ID         NUMBER NOT NULL,
    NAME       VARCHAR2(255),
    TIPO       VARCHAR2(255),
    DADO       BLOB,
    ID_USUARIO NUMBER,
    PRIMARY KEY (ID),
    CONSTRAINT FK_USUARIO_FILES FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);

CREATE SEQUENCE SEQ_FILE
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_USUARIO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CARGO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_ALUNO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_TECNOLOGIA
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CLIENTE
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_VAGA
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_PROGRAMA
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_AVALIACAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_RESERVA_ALOCACAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE NOCYCLE;